# Basic Information 
title: Jinyi Liu
position: Ph.D. candidate in Business Analytics
affiliation: University of Tennessee, Knoxville
affiliation_link: https://haslam.utk.edu/
affiliation_logo: /assets/img/University - HorizLeftLogo-OnOrange (RGB).svg
email: Jinyi.Liu (at) utk.edu

# Search Engine Optimization (SEO)
keywords: Jinyi Liu, Liu Jinyi
canonical: https://jinyi-liu.github.io/
description: Jinyi Liu is a Ph.D. candidate in Business Analytics at Haslam College of Business, University of Tennessee, Knoxville, under the supervision of Prof. Tingliang Huang.
# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=MyXvwGgAAAAJ
github_link: https://github.com/Jinyi-Liu/
linkedin: https://www.linkedin.com/in/jinyi-liu-3372741a6/


# Images 
avatar: /assets/img/profile.png
favicon: /assets/img/favicon.ico
favicon_dark: /assets/img/favicon.ico

# Footnotes
# footnote: Credits to Yaoyao Liu
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
